### ISSUE TITLE
yagmail issue

### ISSUE THREAD

**Issue by ghost** [lumo93/RE-FLEX#21]
I'm currently getting this error when starting this program. Anyone have a solution ??

Traceback (most recent call last):
  File "C:\Users\jddms\Documents\RE-FLEX-main\main.py", line 47, in <module>
    from yagmail_alert import Yagmail
  File "C:\Users\jddms\Documents\RE-FLEX-main\yagmail_alert.py", line 1, in <module>
    import yagmail
ModuleNotFoundError: No module named 'yagmail'

**Comment by redkenusa** [comment]
Try this command and later try again
pip install requests pyaes pbkdf2 yagmail cryptography

**Comment by ghost** [comment]
Ive run this command a few times to no avail.

**Comment by redkenusa** [comment]
Send a picture when you put that command because we need to see the response. I try yesterday that update and is working fine please try execute the command and send a picture

**Comment by ghost** [comment]
I was able to fix it. Went to the folder for the python3 interpreter and ran this command 'pip install requests'
