### ISSUE TITLE
sign in issue

### ISSUE THREAD

**Issue by Azat31** [lumo93/RE-FLEX#8]
Traceback (most recent call last):
  File "C:\Users\aarab\OneDrive\Desktop\RE-FLEX-main\RE-FLEX-main\main.py", line 4, in <module>
    import json_data
  File "C:\Users\aarab\OneDrive\Desktop\RE-FLEX-main\RE-FLEX-main\json_data.py", line 1, in <module>
    import userdata.speed_behavior_values as time

cant Start Main 
please help.

**Comment by lumo93** [comment]
I see the issue, you need to run the speed and behavior script first and save those values

**Comment by Birukggs** [comment]
raceback (most recent call last):
  File "/Users/bloadinggggggg.../Downloads/RE-FLEX-main/main.py", line 1, in <module>
    import requests, json, time, logging, random
ModuleNotFoundError: No module named 'requests'

same problem but i set the speed and behavior script then i get this when run start, not a link that I can copy and paste into a browser

**Comment by lumo93** [comment]
Copy and paste the following command into terminal(Linux) or command prompt(Windows): 

pip install requests pyaes pbkdf2 yagmail

**Comment by MysteryHero** [comment]
im having the same issue , i first thought python was installed in wrong path, i confirm i had pip install. only thing i can come up is becuz i have 11.4 python install of just 11 version ?

**Comment by OkSitD0wn** [comment]
when clicking “Start main” make sure you select the correct python variable at the bottom of the menu. Highlight the appropriate variable and then click “Start main”. If that doesn’t work trying running the script by typing: python3 Script_Dock.py then highlighting “python3” in the aforementioned menu and then start.
